dist: trusty

matrix:
  include:
    - language: php
      php: 7.2
      script:
        - composer selfupdate
        - composer install
        - ./vendor/bin/phpcs --extensions=php --standard=$(pwd)/vendor/joomla/coding-standards/Joomla src/modules
        - ./vendor/bin/phpcs --extensions=php --standard=$(pwd)/vendor/joomla/coding-standards/Joomla src/plugins

    - language: node_js
      node_js: lts/*
      script:
        - npm install
        - gulp parse-template-scss
        - gulp parse-critical-scss

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

sudo: false