dist: trusty

env:
  global:
    secure: "dtkn0UmqSLo9jAczPhowchEHr95qRHjuljO1SOQFz4JEPBGe9fmwGr+u1+Yh91YRDbixTiphLf0ClXtipUptk3gq8XaDMzsgb65InBE7G3wfbfX+cmlh8KPC/8WFU+Jfy8pkyHpNOjeagIymJ98+aJIeTFKsYevewVMEz/lDhRAjchFSCWrbST7SAxmRseKV+A+LxpwqhYBjOu4VKQ7piQpuQcQyJzQrAm5utfMTtNtdSutEtmz0XmABIl/nEY/4f13plnfPYQNMOQGH9uSh7KumHhGuJcf9xaaW/X9iApD8qJyeuutVCmh3VhM29R7cadJnpOJ1WDYVIMUfC+l1tXJPZJDdZTogEDt9Vw2b9pUfA/raWwZq7/zej41GgDEUANgyKvI8C0pz+bBfmXAJOG8ipQEodsY6n4UCSFO3gNDHr0Mi1MX92S7i4ibjG1mGQ1gUcQr3dP3NFl5bvp9bDu9QdAXZzuE4mMgLENnlJyh49gc5e1Bw1ivAmJQxknaFYoeeS/J2qbAHgM5TxdyJwaxMm8cLe2Rh3LLSonUsoxo1TgKxEtnS4hQMdyDtsdLtYBqlvvNnfqfivtgia2Mr/tgcOMnUhwlB4tTodnqikICZBdgvUuz+++JHHGhnRhm9gaYK6IW0jOinGQvLenXcMbrCxsVA9kgZStz+BH7jMCA="

stages:
  - test
  - deploy

before_install:
- openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in siwecosdeploy_rsa.enc -out siwecosdeploy_rsa -d

matrix:
  include:
    - language: php
      stage: test
      php: 7.2
      script:
        - composer selfupdate
        - composer install
        - ./vendor/bin/phpcs --extensions=php --standard=$(pwd)/vendor/joomla/coding-standards/Joomla src/modules
        - ./vendor/bin/phpcs --extensions=php --standard=$(pwd)/vendor/joomla/coding-standards/Joomla src/plugins

    - language: node_js
      stage: test
      node_js: lts/*
      branches:
        only:
        - master
      script:
        - npm install
        - gulp parse-template-scss
        - gulp parse-critical-scss
        - ssh-add -K ./siwecosdeploy_rsa
        - rsync --progress -avz -e "ssh -o StrictHostKeyChecking=no -p 2244" ./src/modules/mod_accountbox ${SFTP_HOST}:/home/web4cshyx/html/siwecos.de/modules
        - rsync --progress -avz -e "ssh -o StrictHostKeyChecking=no -p 2244" ./src/plugins/content/sealoftrust ${SFTP_HOST}:/home/web4cshyx/html/siwecos.de/plugins/content
        - rsync --progress -avz -e "ssh -o StrictHostKeyChecking=no -p 2244" ./src/plugins/content/siwecosapp ${SFTP_HOST}:/home/web4cshyx/html/siwecos.de/plugins/content
        - rsync --progress -avz -e "ssh -o StrictHostKeyChecking=no -p 2244" ./src/plugins/content/siwecosfreescan ${SFTP_HOST}:/home/web4cshyx/html/siwecos.de/plugins/content
        - rsync --progress -avz -e "ssh -o StrictHostKeyChecking=no -p 2244" ./src/templates/siwecos ${SFTP_HOST}:/home/web4cshyx/html/siwecos.de/templates


notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

sudo: required