language: php

dist: trusty

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1

script:
  - composer selfupdate
  - composer install
  - ./vendor/bin/phpcs --extensions=php --standard=$(pwd)/vendor/joomla/coding-standards/Joomla src/modules
  - ./vendor/bin/phpcs --extensions=php --standard=$(pwd)/vendor/joomla/coding-standards/Joomla src/plugins

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

sudo: false